apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: webui-sts
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webui
      env: production
      tier: frontend
  template:
    metadata:
      labels:
        app: webui
        env: production
        tier: frontend
    spec:
      imagePullSecrets:
        - name: santander      
      containers:
        - 
          args:
            - webui.js
          command:
            - node
          image: academiaonline/dockercoins-webui:2.0
          name: webui-container
          ports:
            - 
              containerPort: 8080
              protocol: TCP
          volumeMounts:
            -
              mountPath: /src/files/
              name: webui-files
              readOnly: true
            -
              mountPath: /src/webui.js
              name: webui-volume
              readOnly: true
              subPath: webui.js
          workingDir: /src/
      initContainers:
        -
          args:
            - set -x ; git clone -b openshift --single-branch https://github.com/academiaonline-org/dockercoins ; cp -rv dockercoins/webui/files/* /src/files/
          command:
            - sh
            - -c
          image: bitnami/git:latest
          name: webui-git
          volumeMounts:
            -
              mountPath: /downloads/
              name: webui-downloads
              readOnly: false
            -
              mountPath: /src/files/
              name: webui-files
              readOnly: false
          workingDir: /downloads/
      volumes:
        -
          configMap:
            defaultMode: 0400
            items:
              -
                key: webui.js
                mode: 0400
                path: webui.js
            name: webui-cm
          name: webui-volume
        -
          emptyDir:
            medium: Memory
            sizeLimit: 1Mi
          name: webui-downloads
  volumeClaimTemplates:
    - 
      metadata:
        name: webui-files
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: gp2
        resources:
          requests:
            storage: 1Gi
